### ISSUE TITLE
Linux desktop startup errors

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#93]
## Description

On starting the app on the Linux desktop and clicking Login and after coming back from the Autherization, I see the following errors:

1. Unhandled Exception: UnimplementedError: closeWebView() has not been implemented.
2. Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
3. Some kind of "multiple heros" error

## Why

So that we reduce the possibility of technical debt in code that is developed.

## Close Criteria

- [ ] No exceptions on loging in to the app.

## Detail 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: closeWebView() has not been implemented.
#0      UrlLauncherPlatform.closeWebView (package:url_launcher_platform_interface/src/url_launcher_platform.dart:92:5)
#1      closeInAppWebView (package:url_launcher/src/url_launcher_uri.dart:87:39)
#2      authenticate (package:solid_auth/solid_auth_client.dart:195:5)
<asynchronous suspension>
#3      LoginPageService.loginAndAuth (package:klee/service/login_page_service.dart:34:12)
<asynchronous suspension>
#4      _LoginPageState.build.<anonymous closure> (package:klee/ui/login_page/login_page.dart:137:49)
<asynchronous suspension>

flutter: common_utils e  map init complete
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      Workmanager.initialize (package:workmanager/src/workmanager.dart:151:7)
<asynchronous suspension>


══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
├# Here is the subtree for one of the offending heroes: Hero

When the exception was thrown, this was the stack:
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:283:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:294:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:313:11)
#3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#13     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#15     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#18     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#20     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#22     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#24     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#26     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#28     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#30     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#31     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:67:14)
#32     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#34     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#36     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#38     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#40     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#42     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#43     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#44     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#46     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#48     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#50     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#52     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#53     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6475:16)
#54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#64     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#66     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#68     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#69     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#70     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#72     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#74     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#76     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#78     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#90     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5020:14)
#92     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6363:14)
#94     Element.visitChildElements (package:flutter/src/widgets/framework.dart:3556:5)
#95     Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:331:13)
#96     HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:945:14)
#97     HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:899:11)
#98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#101    _invoke (dart:ui/hooks.dart:145:13)
#102    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#103    _drawFrame (dart:ui/hooks.dart:112:31)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by onionoino** [comment]
I don't have a linux VM, and my hard disk is full now... it is really hard for me to find and solve problems on linux platform... I need to find a linux machine to debug all these issues...

**Comment by gjwgit** [comment]
I'll split into separate issues and test on linux.
