### ISSUE TITLE
LOCATION: Linux requires specific geolocator_linux dependency

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#98]
## Description

Exception on startup `No implementation found for method isLocationServiceEnabled`. 

Seems like `geolocator` does not load `geolocator_linux` automatically, so need to add to `pubspec.yaml`

https://pub.dev/packages/geolocator_linux

## Why

So that our app can strive to be platform independent.

## Closing Criteria

- [x] The Exception is no more since 200b8575eacb2680151efaaee597e8e79b5efe16

## Details

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      GeoUtils.getCurrentLocation (package:klee/utils/geo_utils.dart:21:22)
<asynchronous suspension>
```

**Comment by gjwgit** [comment]
Whilst the Exception is no more after adding `geolocator_linux` the new package raises the following Exception which needs to be caught and dealt with?

```
Unhandled Exception: Location services are disabled.
```
